### ISSUE TITLE
gonna release it?

### ISSUE THREAD

**Issue by ghost** [pattern-f/TQ-pre-jailbreak#1]

**Comment by ClarityG** [comment]
C0met isn't even a real jailbreak lmfao.

**Comment by Meet-1504** [comment]
Please Release

**Comment by ClarityG** [comment]
C0met isn't even a real jailbreak lmfao.

**Comment by ghost** [comment]
> C0met isn't even a real jailbreak lmfao.

nope thats a missleading information. why you guys believe all the news posted on youtube/twitter. REAL!

**Comment by DramaBinny** [comment]
maverickdev is a loser
